version: "3.7"
services:
  api:
    image: rust:1.39-stretch
    working_dir: /rust/src
    volumes:
      - .:/rust/src
    environment:
      SHORT_URL_DB_IP: db
      HOSTNAME: api
      SHORT_URL_DB_USER: short
      SHORT_URL_DB_PASSWORD: url
      SHORT_URL_DB_NAME: short_url
      SHORT_URL_DB_PORT: 3306
    ports:
      - 8080:8080
    tty: true

  db:
    image: mysql:5.7.28
    volumes:
      - ./script:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: short_url
      MYSQL_USER: short
      MYSQL_PASSWORD: url